### ISSUE TITLE
上传视频

### ISSUE THREAD

**Issue by dxcweb** [dxcweb/local-ai#1]
https://github.com/dxcweb/local-ai/assets/21973553/5c741b97-6fd8-436a-bc8b-99c4fb113ea0

https://github.com/dxcweb/local-ai/assets/21973553/06572f8b-a1d6-4457-9805-b82642c3e302

**Comment by mfkscq** [comment]
from Tastapi import
loduleNotFoundError: No module named 'fastapi' 

这个怎么解决，macos
