### ISSUE TITLE
Intel Mac 提示找不到 fastapi 模块

### ISSUE THREAD

**Issue by mfkscq** [dxcweb/local-ai#3]
Traceback (most recent call last):
  File "/Applications/本地AI.app/Contents/Resources/lib/stable_diffusion_webui/webui.py", line 11, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'

**Comment by dxcweb** [comment]
抱歉我并没复现您反馈的问题。
rm -rf /Applications/本地AI.app/Contents/Resources/lib/stable_diffusion_webui/completed.dxc
使用这个命令删除该文件，重起应用会重新安装一次依赖，请尝试

**Comment by mfkscq** [comment]
他们m2的没问题，Intel的就容易出现找不到这个模块那个模块的问题

**Comment by mfkscq** [comment]
他们m2的没问题，Intel的就容易出现找不到这个模块那个模块的问题。尝试了，还是不行……
